spring:
  application:
    name: consumer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: steff
    password: 123456
  amqp:
    deserialization:
      trust:
        all: true
      whitelist:
        patterns:
          - "org.rabbitmq.dtos.*"

server:
  port: 8082

logging:
  level:
    org.springframework.amqp: DEBUG
